services:
  usermanagerms:
    image: usermanagerms
    build:
      context: .
      dockerfile: UserManagerMS/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5001
  petsmanagerms:
    image: petsmanagerms
    build:
      context: .
      dockerfile: PetsManagerMS/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
  adoptionmanagerms:
    image: adoptionmanagerms
    build:
      context: .
      dockerfile: AdoptionManagerMS/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5003